### ISSUE TITLE
App Crash on start with android@11.0.0 targetsdk 32 in device with api <29

### ISSUE THREAD

**Issue by myzzib** [andreszs/cordova-plugin-in-app-update#2]
Hi, with android@11.0.0, with target sdk 32 an app crash in device with api<29 no problem in device with api 33.
I test in in hello word application with config.xml

<?xml version='1.0' encoding='utf-8'?>
<widget id="com.example.hello" version="1.0.0" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>HelloWorld</name>
    <description>Sample Apache Cordova App</description>
    <author email="dev@cordova.apache.org" href="https://cordova.apache.org">
        Apache Cordova Team
    </author>
    <content src="index.html" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
 
 
  <preference name="android-minSdkVersion" value="22" />
  <preference name="android-targetSdkVersion" value="32" />
</widget>

Only this plugin installed, this cordova info text.

Cordova Packages:

    cli: 11.1.0
        common: 4.1.0
        create: 4.1.0
        lib: 11.1.0
            common: 4.1.0
            fetch: 3.1.0
            serve: 4.0.1

Project Installed Platforms:

    android: 11.0.0

Project Installed Plugins:

    cordova-plugin-in-app-updates: 2.0.5

Environment:

    OS: Microsoft Windows 11 Pro 10.0.22621 (22621) (Windows 10.0.22621) x64
    Node: v18.12.1
    npm: 9.4.2

android Environment:

    android:
ERROR: Command failed with exit code 1: avdmanager list target
"avdmanager" non � riconosciuto come comando interno o esterno,
 un programma eseguibile o un file batch.

Project Setting Files:

    config.xml:
<?xml version='1.0' encoding='utf-8'?>
<widget id="com.example.hello" version="1.0.0" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>HelloWorld</name>
    <description>Sample Apache Cordova App</description>
    <author email="dev@cordova.apache.org" href="https://cordova.apache.org">
        Apache Cordova Team
    </author>
    <content src="index.html" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />

  <preference name="android-minSdkVersion" value="22" />
  <preference name="android-targetSdkVersion" value="32" />
</widget>

    package.json:
--- Start of Cordova JSON Snippet ---
{
  "platforms": [
    "android"
  ],
  "plugins": {
    "cordova-plugin-in-app-updates": {
      "ANDROIDX_APPCOMPAT_VERSION": "1.3.0",
      "ANDROID_PLAY_CORE_VERSION": "1.8.0",
      "ANDROID_MATERIAL_VERSION": "1.2.0"
    }
  }
}

Thanks a lot
Regards,
Maurizio

**Comment by andreszs** [comment]
This was caused by the override of the `android:theme` from the app's **AndroidManifest.xml**. The workaround was to add this into your **config.xml** to restore the correct theme:

```
<edit-config file="app/src/main/AndroidManifest.xml" mode="merge" target="/manifest/application">
    <activity android:theme="@style/Theme.App.SplashScreen"></activity>
</edit-config>
```

Latest version **2.1.0** just released does not modify the theme anymore and is 100% working with cordova-android@11.
Upcoming version **2.2.0** to be released tomorrow will correctly target SDK 33 for cordova-android@12.
